### ISSUE TITLE
Please make sure text/media file can be previewable

### ISSUE THREAD

**Issue by colinkiama** [kommanderapp/kmd-uwp#78]
Like on MacOS. It would really be awesome if you could preview SVG images too because even Windows Explorer can't even do that yet! Thanks 👍

**Comment by arkoc** [comment]
Thank you, for your contribution. I think it reasonable and will be in included in major v1 release.

**Comment by colinkiama** [comment]
Awesome! I really appreciate all the work you guys have done on this!

Sent from Mail for Windows 10
